### ISSUE TITLE
Improving code - error on select prompt file

### ISSUE THREAD

**Issue by Lucas-Lanna** [gpt-engineer-org/gpt-engineer#995] opened 2024-01-31 17:38 UTC
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

I'm tryng to improve an application

## Current Behavior

When I remove the # from prompt file, this is the error:

Please select and deselect (add # in front) files, save it, and close it to continue...
Traceback (most recent call last):
  File "C:\Users\pouco\AppData\Local\pypoetry\Cache\virtualenvs\gpt-engineer-iH5RqDsZ-py3.11\Scripts\gpte", line 6, in <module>
    sys.exit(app())
             ^^^^^

  File "C:\Users\pouco\Dropbox\X\Codigos\gpt-engineer\gptengineer\applications\cli\main.py", line 190, in main
    files_dict = fileselector.ask_for_files()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pouco\Dropbox\X\Codigos\gpt-engineer\gpt_engineer\applications\cli\file_selector.py", line 66, in ask_for_files
    selected_files = self.editor_file_selector(self.project_path, True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pouco\Dropbox\X\Codigos\gpt-engineer\gpt_engineer\applications\cli\file_selector.py", line 139, in editor_file_selector
    return self.get_files_from_toml(
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pouco\Dropbox\X\Codigos\gpt-engineer\gpt_engineer\applications\cli\file_selector.py", line 195, in get_files_from_toml
    for file,  in edited_tree["files"].items():
                   ~~~^^^^^^^^^

KeyError: 'files'

## Failure Information

Information about the failure, including environment details, such as LLM used.

### Steps to Reproduce

If possible, provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Any relevant log snippets or files here.

**Comment by kristiankyvik** [comment] 2024-02-01 09:07
Hi @Lucas-Lanna,

Would you mind filling in the `Steps to Reproduce` section of the issue?

The following would be especially useful:
- The exact command(s) you are using to run the gpte in your terminal
- A .zip of the directory you are running this command within

**Comment by similato87** [comment] 2024-02-19 04:11
Hi @Lucas-Lanna , thanks for raising this issue. This will not happen again as such bug has been fixed in a recent commit. The prompt file will automatically transfer to LLMs and you won't have to worry about it.

**Comment by onyxdevs** [comment] 2024-02-22 07:47
Hello @Lucas-Lanna,

I had the same issue and in my case, the problem was that I hadn't selected any files, we should go to `projects/PROJECT_NAME/.gpteng/file_selection.toml` as described in the error message `Please select and deselect (add # in front) files, save it, and close it to continue ` and select the files to be sent to GPT.

Maybe my case helps someone 🙂.

**Closed** 2024-02-22 18:29 UTC
Labels: bug, triage
